#!/bin/bash

LC_ALL=C
export LC_ALL

list=$1

function test_devel_packages {
    if grep -e "-devel" >/dev/null $1; then
        test_status=FAIL
    fi
}

function run_test {
    func=$1
    shift

    test_status=PASS

    echo -n "Running $func... "
    $func $*
    echo $test_status
    [ $test_status = "FAIL" ] && exit 1
}

run_test test_devel_packages $list
