#!/bin/bash

# We generate a list of OBS packages from a list of rpm packages stored in a
# file given as the first argument

bin_path=`dirname $0`
db_path=$(cd $bin_path/../data; pwd)
db=$db_path/rpmpackage2obspackagedb

rpms_raw=$1

# strip the version from the rpm names
rpm_packages=`sed -e 's/\..*$//' $rpms_raw`

tmp=`mktemp`

for rpm_package in $rpm_packages; do
    map=`grep $rpm_package\; $db`
    if [ $? == 1 ]; then
        echo "Package '$rpm_package' not found in db" 1>&2
        continue
    fi

    obs_package=`echo $map | sed 's/^.*;//'`
    echo $obs_package >> $tmp
done

sort $tmp | uniq

rm -f $tmp
